//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsgtUITest.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsigneeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsigneeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsgtUITest.Resource.ConsigneeResource", typeof(ConsigneeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUDU61SSZ005610X.
        /// </summary>
        internal static string PaymentHistoryBOL_Consignee {
            get {
                return ResourceManager.GetString("PaymentHistoryBOL_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILL.
        /// </summary>
        internal static string PaymentHistoryCustomer_Consignee {
            get {
                return ResourceManager.GetString("PaymentHistoryCustomer_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILL.
        /// </summary>
        internal static string PaymentHistoryFromAmount_Consignee {
            get {
                return ResourceManager.GetString("PaymentHistoryFromAmount_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB1259016.
        /// </summary>
        internal static string PaymentHistoryInvoiceNo_Consignee {
            get {
                return ResourceManager.GetString("PaymentHistoryInvoiceNo_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILL.
        /// </summary>
        internal static string PaymentHistoryPaymentRef_Consignee {
            get {
                return ResourceManager.GetString("PaymentHistoryPaymentRef_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILL.
        /// </summary>
        internal static string PaymentHistoryToAmount_Consignee {
            get {
                return ResourceManager.GetString("PaymentHistoryToAmount_Consignee", resourceCulture);
            }
        }
    }
}
