///------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsgtUITest.Resource
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashBoardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashBoardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsgtUITest.Resource.DashBoardResource", typeof(DashBoardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kumar.
        /// </summary>
        internal static string ApplicantName_Consignee {
            get {
                return ResourceManager.GetString("ApplicantName_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bayan_Agent {
            get {
                return ResourceManager.GetString("Bayan_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bayan_Broker {
            get {
                return ResourceManager.GetString("Bayan_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bayan_Consignee {
            get {
                return ResourceManager.GetString("Bayan_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Bayan_Transporter {
            get {
                return ResourceManager.GetString("Bayan_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BOL_Agent {
            get {
                return ResourceManager.GetString("BOL_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BOL_Broker {
            get {
                return ResourceManager.GetString("BOL_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BOL_Consignee {
            get {
                return ResourceManager.GetString("BOL_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BOL_Transporter {
            get {
                return ResourceManager.GetString("BOL_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC IMport &amp; Export.
        /// </summary>
        internal static string CompanyName_Consignee {
            get {
                return ResourceManager.GetString("CompanyName_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRKU5314409.
        /// </summary>
        internal static string Container_Agent {
            get {
                return ResourceManager.GetString("Container_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCNU8353904.
        /// </summary>
        internal static string Container_Broker {
            get {
                return ResourceManager.GetString("Container_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNBU9014020.
        /// </summary>
        internal static string Container_Consignee {
            get {
                return ResourceManager.GetString("Container_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENU5005467.
        /// </summary>
        internal static string Container_Transporter {
            get {
                return ResourceManager.GetString("Container_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Designation_Consignee {
            get {
                return ResourceManager.GetString("Designation_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DischargeDate_Agent {
            get {
                return ResourceManager.GetString("DischargeDate_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DischargeDate_Broker {
            get {
                return ResourceManager.GetString("DischargeDate_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DischargeDate_Consignee {
            get {
                return ResourceManager.GetString("DischargeDate_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dwelldays_Agent {
            get {
                return ResourceManager.GetString("Dwelldays_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dwelldays_Broker {
            get {
                return ResourceManager.GetString("Dwelldays_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Dwelldays_Consignee {
            get {
                return ResourceManager.GetString("Dwelldays_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD.
        /// </summary>
        internal static string ESBilling_Consignee {
            get {
                return ResourceManager.GetString("ESBilling_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD.
        /// </summary>
        internal static string ESDelivery_Consignee {
            get {
                return ResourceManager.GetString("ESDelivery_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD.
        /// </summary>
        internal static string ESexperience_Consignee {
            get {
                return ResourceManager.GetString("ESexperience_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD.
        /// </summary>
        internal static string ESShipment_Consignee {
            get {
                return ResourceManager.GetString("ESShipment_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GatedoutDate_Agent {
            get {
                return ResourceManager.GetString("GatedoutDate_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GatedoutDate_Broker {
            get {
                return ResourceManager.GetString("GatedoutDate_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GatedoutDate_Consignee {
            get {
                return ResourceManager.GetString("GatedoutDate_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NoofVisitors_Consignee {
            get {
                return ResourceManager.GetString("NoofVisitors_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILL.
        /// </summary>
        internal static string OpportunitiesIssueIdentified_Consignee {
            get {
                return ResourceManager.GetString("OpportunitiesIssueIdentified_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRKU5314409.
        /// </summary>
        internal static string Search_Agent {
            get {
                return ResourceManager.GetString("Search_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCNU8353904.
        /// </summary>
        internal static string Search_Broker {
            get {
                return ResourceManager.GetString("Search_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNBU9014020.
        /// </summary>
        internal static string Search_Consignee {
            get {
                return ResourceManager.GetString("Search_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENU5005467.
        /// </summary>
        internal static string Search_Transporter {
            get {
                return ResourceManager.GetString("Search_Transporter", resourceCulture);
            }
        }
    }
}
