//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsgtUITest.Resource
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsgtUITest.Resource.LoginResource", typeof(LoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRKU5314409.
        /// </summary>
        internal static string Container_Agent {
            get {
                return ResourceManager.GetString("Container_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCNU8353904.
        /// </summary>
        internal static string Container_Broker {
            get {
                return ResourceManager.GetString("Container_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNBU9014020.
        /// </summary>
        internal static string Container_Consignee {
            get {
                return ResourceManager.GetString("Container_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCIU1825515.
        /// </summary>
        internal static string Container_Transporter {
            get {
                return ResourceManager.GetString("Container_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0234567891.
        /// </summary>
        internal static string Mobile_Agent {
            get {
                return ResourceManager.GetString("Mobile_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789.
        /// </summary>
        internal static string Mobile_Broker {
            get {
                return ResourceManager.GetString("Mobile_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8745612309.
        /// </summary>
        internal static string Mobile_Consignee {
            get {
                return ResourceManager.GetString("Mobile_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7894561230.
        /// </summary>
        internal static string Mobile_Transporter {
            get {
                return ResourceManager.GetString("Mobile_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 777.
        /// </summary>
        internal static string OTP_Agent {
            get {
                return ResourceManager.GetString("OTP_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 777.
        /// </summary>
        internal static string OTP_Broker {
            get {
                return ResourceManager.GetString("OTP_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 777.
        /// </summary>
        internal static string OTP_Consignee {
            get {
                return ResourceManager.GetString("OTP_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 777.
        /// </summary>
        internal static string OTP_Transporter {
            get {
                return ResourceManager.GetString("OTP_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string Password_Agent {
            get {
                return ResourceManager.GetString("Password_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string Password_Broker {
            get {
                return ResourceManager.GetString("Password_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        internal static string Password_Consignee {
            get {
                return ResourceManager.GetString("Password_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string Password_Transporter {
            get {
                return ResourceManager.GetString("Password_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cieloclearingagent@gmail.com.
        /// </summary>
        internal static string Username_Agent {
            get {
                return ResourceManager.GetString("Username_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cielobroker1@gmail.com.
        /// </summary>
        internal static string Username_Broker {
            get {
                return ResourceManager.GetString("Username_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cieloconsignee@gmail.com.
        /// </summary>
        internal static string Username_Consignee {
            get {
                return ResourceManager.GetString("Username_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cielotransporter1@gmail.com.
        /// </summary>
        internal static string Username_Transporter {
            get {
                return ResourceManager.GetString("Username_Transporter", resourceCulture);
            }
        }
    }
}
