//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsgtUITest.Resource
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterUserArabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterUserArabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsgtUITest.Resource.RegisterUserArabic", typeof(RegisterUserArabic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Addi_Customertype {
            get {
                return ResourceManager.GetString("Addi_Customertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD1.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo1 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD2.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo2 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD3.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo3 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD4.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo4 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD5.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo5 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD6.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo6 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFG7.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo7 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFG8.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo8 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFG9.
        /// </summary>
        internal static string Addi_import_Export_AdditionNo9 {
            get {
                return ResourceManager.GetString("Addi_import_Export_AdditionNo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEFDF12.
        /// </summary>
        internal static string Addi_Import_Export_LicenseNo {
            get {
                return ResourceManager.GetString("Addi_Import_Export_LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8558.
        /// </summary>
        internal static string Addi_NationalAddress {
            get {
                return ResourceManager.GetString("Addi_NationalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hassan1Avenue.
        /// </summary>
        internal static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timber comapny.
        /// </summary>
        internal static string Com_CompanyName {
            get {
                return ResourceManager.GetString("Com_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nan_ {
            get {
                return ResourceManager.GetString("Nan_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79589.
        /// </summary>
        internal static string Nan_Additionalno {
            get {
                return ResourceManager.GetString("Nan_Additionalno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1230.
        /// </summary>
        internal static string Nan_Buildno {
            get {
                return ResourceManager.GetString("Nan_Buildno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jaddah.
        /// </summary>
        internal static string Nan_Districtname {
            get {
                return ResourceManager.GetString("Nan_Districtname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 789456.
        /// </summary>
        internal static string Nan_Fax {
            get {
                return ResourceManager.GetString("Nan_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hassan AL Banna St..
        /// </summary>
        internal static string Nan_Streetname {
            get {
                return ResourceManager.GetString("Nan_Streetname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7894612312.
        /// </summary>
        internal static string Nan_Telephone {
            get {
                return ResourceManager.GetString("Nan_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS123.
        /// </summary>
        internal static string Nan_Unitno {
            get {
                return ResourceManager.GetString("Nan_Unitno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 456145.
        /// </summary>
        internal static string Nan_Zipcode {
            get {
                return ResourceManager.GetString("Nan_Zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string PerConfirmPassword {
            get {
                return ResourceManager.GetString("PerConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timbbbergoods@gmail.com.
        /// </summary>
        internal static string PerEmailAddress {
            get {
                return ResourceManager.GetString("PerEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed.
        /// </summary>
        internal static string PerFirstNameArabic {
            get {
                return ResourceManager.GetString("PerFirstNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed.
        /// </summary>
        internal static string PerFirstNameEnglish {
            get {
                return ResourceManager.GetString("PerFirstNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        internal static string PerJobTitle {
            get {
                return ResourceManager.GetString("PerJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabi.
        /// </summary>
        internal static string PerLastNameArabic {
            get {
                return ResourceManager.GetString("PerLastNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabi.
        /// </summary>
        internal static string PerLastNameEnglish {
            get {
                return ResourceManager.GetString("PerLastNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9774444442.
        /// </summary>
        internal static string PerMobile {
            get {
                return ResourceManager.GetString("PerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string PerPassword {
            get {
                return ResourceManager.GetString("PerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 777.
        /// </summary>
        internal static string SENDOTP_REGISTERATION {
            get {
                return ResourceManager.GetString("SENDOTP_REGISTERATION", resourceCulture);
            }
        }
    }
}
