//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsgtUITest.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsgtUITest.Resource.RequestResource", typeof(RequestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestFileComplaintMessage_Agent {
            get {
                return ResourceManager.GetString("RequestFileComplaintMessage_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestFileComplaintMessage_Broker {
            get {
                return ResourceManager.GetString("RequestFileComplaintMessage_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestFileComplaintMessage_Consignee {
            get {
                return ResourceManager.GetString("RequestFileComplaintMessage_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestFileComplaintMessage_Transporter {
            get {
                return ResourceManager.GetString("RequestFileComplaintMessage_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestFileComplaintTitle_Agent {
            get {
                return ResourceManager.GetString("RequestFileComplaintTitle_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestFileComplaintTitle_Broker {
            get {
                return ResourceManager.GetString("RequestFileComplaintTitle_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestFileComplaintTitle_Consignee {
            get {
                return ResourceManager.GetString("RequestFileComplaintTitle_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestFileComplaintTitle_Transporter {
            get {
                return ResourceManager.GetString("RequestFileComplaintTitle_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestForMessge_Agent {
            get {
                return ResourceManager.GetString("RequestForMessge_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestForMessge_Broker {
            get {
                return ResourceManager.GetString("RequestForMessge_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestForMessge_Consignee {
            get {
                return ResourceManager.GetString("RequestForMessge_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestForMessge_Transporter {
            get {
                return ResourceManager.GetString("RequestForMessge_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestForService_Agent {
            get {
                return ResourceManager.GetString("RequestForService_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestForService_Broker {
            get {
                return ResourceManager.GetString("RequestForService_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestForService_Consignee {
            get {
                return ResourceManager.GetString("RequestForService_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestForService_Transporter {
            get {
                return ResourceManager.GetString("RequestForService_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestInfoMessage_Agent {
            get {
                return ResourceManager.GetString("RequestInfoMessage_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestInfoMessage_Broker {
            get {
                return ResourceManager.GetString("RequestInfoMessage_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestInfoMessage_Consignee {
            get {
                return ResourceManager.GetString("RequestInfoMessage_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inilization of Cloud Server.
        /// </summary>
        internal static string RequestInfoMessage_Transporter {
            get {
                return ResourceManager.GetString("RequestInfoMessage_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestInfoTitle_Agent {
            get {
                return ResourceManager.GetString("RequestInfoTitle_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestInfoTitle_Broker {
            get {
                return ResourceManager.GetString("RequestInfoTitle_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestInfoTitle_Consignee {
            get {
                return ResourceManager.GetString("RequestInfoTitle_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Complaint for 3rd party Service.
        /// </summary>
        internal static string RequestInfoTitle_Transporter {
            get {
                return ResourceManager.GetString("RequestInfoTitle_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8795.
        /// </summary>
        internal static string Ticketno_Agent {
            get {
                return ResourceManager.GetString("Ticketno_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23012.
        /// </summary>
        internal static string Ticketno_Broker {
            get {
                return ResourceManager.GetString("Ticketno_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012.
        /// </summary>
        internal static string Ticketno_Consignee {
            get {
                return ResourceManager.GetString("Ticketno_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25897.
        /// </summary>
        internal static string Ticketno_Tansporter {
            get {
                return ResourceManager.GetString("Ticketno_Tansporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service request.
        /// </summary>
        internal static string TicketSearchBox_Agent {
            get {
                return ResourceManager.GetString("TicketSearchBox_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service request.
        /// </summary>
        internal static string TicketSearchBox_Broker {
            get {
                return ResourceManager.GetString("TicketSearchBox_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service request.
        /// </summary>
        internal static string TicketSearchBox_Consignee {
            get {
                return ResourceManager.GetString("TicketSearchBox_Consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service request.
        /// </summary>
        internal static string TicketSearchBox_Transporter {
            get {
                return ResourceManager.GetString("TicketSearchBox_Transporter", resourceCulture);
            }
        }
    }
}
