//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsgtApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RSGT_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSGT_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsgtApp.RSGT_Resource", typeof(RSGT_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hl4bA4nB4yI0fC8fH7eT6.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROD.
        /// </summary>
        public static string AppMode {
            get {
                return ResourceManager.GetString("AppMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5fc756ed33eebe7e6001b8b5709b257f91de4e989501a90ab805ad72.
        /// </summary>
        public static string AuthorizationKey {
            get {
                return ResourceManager.GetString("AuthorizationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000000.
        /// </summary>
        public static string ColletionViewPageSize {
            get {
                return ResourceManager.GetString("ColletionViewPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczarn6d78NHwo31AaZVKmMmJ2jEo55E7+MFfz8JiUkHRhe7MkvozL+3yj.
        /// </summary>
        public static string ContentUrlDVMT {
            get {
                return ResourceManager.GetString("ContentUrlDVMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczapqcDM0/AcHitxKSsBYtBBHdvCT+uvDqJXUdS+VA7WSiV1tK/a3PNw+U20XlSP6qO0=.
        /// </summary>
        public static string ContentUrlPROD {
            get {
                return ResourceManager.GetString("ContentUrlPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string IndicatorViewBGColor {
            get {
                return ResourceManager.GetString("IndicatorViewBGColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        public static string IndicatorViewOpacity {
            get {
                return ResourceManager.GetString("IndicatorViewOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4.
        /// </summary>
        public static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczar7/rB2mbLi/HNWKw2XkLlvalDkikeTj3A=.
        /// </summary>
        public static string MobCMSUrl {
            get {
                return ResourceManager.GetString("MobCMSUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczaqu6ZOdKMGpu9/usyx2eUn33H3IlXzgUYfWwImDOSx2BBU3XzG/f6xfXtbUWMscOZ6CaJfKWetdvMLVPe31WOCh.
        /// </summary>
        public static string MobPaymentDVMT {
            get {
                return ResourceManager.GetString("MobPaymentDVMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczaqq9m0hgtjnGsWV+KPCpxNS0Q8Q67v9agQ48nVjEcJ5aa+5+M6CAmZ9565NUOpdkhwJZK+K7Z6FCg==.
        /// </summary>
        public static string MobPaymentPROD {
            get {
                return ResourceManager.GetString("MobPaymentPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczaqu6ZOdKMGpu9/usyx2eUn33H3IlXzgUYcT9HTUHJOW5A==.
        /// </summary>
        public static string MobWebUrlDVMT {
            get {
                return ResourceManager.GetString("MobWebUrlDVMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczaqq9m0hgtjnGsWV+KPCpxNSBvFWUsapnYM=.
        /// </summary>
        public static string MobWebUrlPROD {
            get {
                return ResourceManager.GetString("MobWebUrlPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATIC.
        /// </summary>
        public static string OTP_Key {
            get {
                return ResourceManager.GetString("OTP_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.17.
        /// </summary>
        public static string VersionNo {
            get {
                return ResourceManager.GetString("VersionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string WalletFlag {
            get {
                return ResourceManager.GetString("WalletFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczaqu6ZOdKMGpu9/usyx2eUn33H3IlXzgUYdI3cOz7v4FGqQ/Ip07MnnuY4wYrnCPftuBXqaQhl27dw==.
        /// </summary>
        public static string WalletPaymentUrlDVMT {
            get {
                return ResourceManager.GetString("WalletPaymentUrlDVMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j/66uzxczaqq9m0hgtjnGsWV+KPCpxNSADD7SCVViuM3ZdOaw7nD/Djm3ZqmB/YiBvFWUsapnYM=.
        /// </summary>
        public static string WalletPaymentUrlPROD {
            get {
                return ResourceManager.GetString("WalletPaymentUrlPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        public static string WebApiTimeOut {
            get {
                return ResourceManager.GetString("WebApiTimeOut", resourceCulture);
            }
        }
    }
}
